# ========== 游戏设置 ==========
emulator:
  type: "雷电" # 模拟器类型
  start_cmd: C:\LDPlayer\LDPlayer9\dnplayer.exe
  config_file: ""

LOG_PATH: "log"
DELAY: 2

account:
password:

# ========== Logger设置 ==========
DEBUG: False
SHOW_MAP_NODE: False
SHOW_ANDROID_INPUT: False
SHOW_ENEMY_RULES: False
SHOW_FIGHT_STAGE: False
SHOW_CHAPTER_INFO: False
SHOW_MATCH_FIGHT_STAGE: False
SHOW_DECISIVE_BATTLE_INFO: False
SHOW_OCR_INFO: False

# ========== 日常挂机策略设置 ==========
daily_automation:
  auto_expedition: True # 自动重复远征
  auto_gain_bonus: True # 当有任务完成时自动点击
  auto_bath_repair: True # 空闲时自动澡堂修理

  dock_full_destroy: True # 船坞已满时自动清空，若设置为false则船坞已满后终止所有常规出征任务

  auto_battle: True # 自动打完每日战役次数
  battle_type: "困难潜艇" # 打哪个。可选名称参考"plans/battle/"

  auto_normal_fight: True # 按自定义任务进行常规战
  normal_fight_tasks: [] # 自动出征任务用列表 [plan名，舰队号，目标成功次数] 表示，按顺序从上往下执行。plan名参考"plans/normal_fight/"

SHIP_NAME_PATH: data/ship_names.yaml
PLAN_ROOT: data/plans
